# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9d6d706c187e98cab01fad90e2bc5e31bb8142e883268f1ff601704104e805b94628946ab9e2665ab9834064fa13bc992aaed150c8d8d53835ea712a143929

test:
  secret_key_base: 62e64ed2507690e998ad77bb91a45374fd0fb415232bfebd6d8e4ce9729fc5f3f00d9ddbe7b974a4c813c21e7ed599705e8120b16741b3d0b778bc06e092975e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
